export const FilterList = [
  {
    key: 1,
    value: "Energía",
    isSelected: true,
  },
  {
    key: 2,
    value: "Entretenimiento",
    isSelected: false,
  },
  {
    key: 3,
    value: "Fiesta",
    isSelected: false,
  },
  {
    key: 4,
    value: "Relajación",
    isSelected: false,
  },
  {
    key: 5,
    value: "Viaje diario",
    isSelected: false,
  },
  {
    key: 6,
    value: "Para sentirte bien",
    isSelected: false,
  },
  {
    key: 7,
    value: "Triste",
    isSelected: false,
  },
  {
    key: 8,
    value: "Romance",
    isSelected: false,
  },
  {
    key: 9,
    value: "Concentración",
    isSelected: false,
  },
  {
    key: 10,
    value: "Sueño",
    isSelected: false,
  },
];

export const ListenAgain = [
  {
    key: 1,
    isAlbum: true,
    imageSource: "src/assets/static/images/albumsImage/07e12ccaff200ac1214f42ac2c466f1a.png",
    artist: "Various",
    playlistName: "Top 100 Argentina",
    songName: "none",
    songs: 305,
    views: 0,
  },
  {
    key: 2,
    isAlbum: false,
    imageSource: "src/assets/static/images/albumsImage/92d2f58023ddb67411ab73f18a6358c4.png",
    artist: "Boris Brejcha",
    playlistName: "none",
    songName: "The Final",
    songs: 0,
    views: 6350,
  },
  {
    key: 3,
    isAlbum: true,
    imageSource: "src/assets/static/images/albumsImage/58b9b28e29d52bd7f484b799db3341f6.png",
    artist: "The Weeknd",
    playlistName: "Starboy",
    songName: "none",
    songs: 33,
    views: 0,
  },
  {
    key: 4,
    isAlbum: false,
    imageSource: "src/assets/static/images/albumsImage/758c2683a632d5521796b21be90d9541.png",
    artist: "Ania Szarmach",
    playlistName: "none",
    songName: "Shades of Love",
    songs: 0,
    views: 3500,
  },
  {
    key: 5,
    isAlbum: true,
    imageSource: "src/assets/static/images/albumsImage/42436ccdebd6e39a8dfe9b8fefa6d142.png",
    artist: "Roosevelt",
    playlistName: "Midnight Versions",
    songName: "none",
    songs: 68,
    views: 0,
  },
  {
    key: 6,
    isAlbum: true,
    imageSource: "src/assets/static/images/albumsImage/3b02630be867dbdbd629e9d32572a9b5.png",
    artist: "Liking Park",
    playlistName: "Hybrid Theory",
    songName: "none",
    songs: 12,
    views: 0,
  },
]